/**
 * All disclaimer and micro-disclaimer content for NUMERON.
 * Centralised here so UI components can import by key.
 */

/** First-visit persistent banner */
export const DISCLAIMER_BANNER = {
  title: '> NUMERON v1.2 // INITIALISING',
  lines: [
    '> ENTERTAINMENT PURPOSES ONLY',
    '> No scientific basis. Not life advice.',
    '> Digit sums are fun. They are not destiny.',
  ],
  prompt: '> Do you understand?',
  buttonText: 'ACKNOWLEDGED',
} as const;

/** PDF report — every page footer (8pt) */
export const PDF_FOOTER_DISCLAIMER =
  'This report is generated by NUMERON (Retroverse Studios) for entertainment and cultural exploration only. Numerology has no scientific basis and no demonstrated predictive validity. Nothing in this report constitutes life advice, financial advice, medical advice, career guidance, relationship guidance, or professional advice of any kind. Do not make significant decisions based on the contents of this report. If you are facing a difficult decision, consult a qualified professional or a trusted person in your life.';

/** PDF report — cover page notice */
export const PDF_COVER_NOTICE = {
  heading: 'For Entertainment & Cultural Exploration Only',
  body: 'NUMERON explores numerology as a rich cross-cultural tradition with a fascinating mathematical structure. It is not a predictive system, and this report is not advice of any kind. The digit sum of your name does not determine your future. You do.',
} as const;

/**
 * Per-feature micro-disclaimers.
 * Each keyed to a feature identifier used by UI components.
 */
export const microDisclaimers: Record<string, string> = {
  lifePath:
    'Calculation method varies between traditions. See System Comparison for how results differ.',

  systemComparison:
    'These systems produce different results for the same input. There is no agreed method to determine which (if any) is correct.',

  personalTiming: 'Personal timing numbers are entertainment, not scheduling advice.',

  compatibility:
    'Numerological compatibility has no scientific basis. Please do not break up with anyone over this.',

  fineStructure:
    '137 is genuinely mysterious in physics. The numerological framing is entirely ours.',

  planckFull:
    'We chose 9 significant figures because 33 is more interesting than 2. This is honest cherry-picking.',

  sudokuCertificate:
    'The maths here is completely real. The cosmic significance is entirely made up.',

  masterNumber:
    'Master numbers are a Western numerology convention, not present in all traditions.',

  karmaDebt:
    '"Karma debt" is a metaphor used in some numerology traditions. It is not a statement about your moral character or past lives.',

  constantsGeneral:
    'The scientific constants table cherry-picks digit counts to produce interesting results. We say so explicitly.',

  ninesCluster:
    'Any multiple of 9 always reduces to 9 — it is a property of base-10 arithmetic, not a cosmic coincidence.',
} as const;
